server:
  port: 0
spring:
  application:
    name: investments-service
  config:
    import: "classpath:api-keys.yaml"
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio_db
    username: postgres
    password: Bgl862304*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  logging:
    level:
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.description.sql.BasicBinder: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
api:
  coingecko:
    url: https://api.coingecko.com/api/v3/